name: elements_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Network
  http: ^1.1.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1

  # State Management
  provider: ^6.0.5

  # Analysis
  very_good_analysis: ^5.1.0

  # UI 
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  animated_button: ^0.2.0
  like_button: ^2.0.5
  neon_widgets: ^2.0.0
  
  # Network 
  connectivity_plus: ^5.0.1

  # Ads
  google_mobile_ads: ^3.1.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/playstore.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/img/my-logo-removebg.png"
 


flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/svg/
    - assets/img/

